version: '3.8'

services:
  ollama:
    image: ollama/ollama:latest
    container_name: ollama-chatbot
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama
    environment:
      - OLLAMA_HOST=0.0.0.0
    restart: unless-stopped

  chatbot:
    build: .
    container_name: chatbot-app
    volumes:
      - .:/app
      - ./docs:/app/docs
    depends_on:
      - ollama
    environment:
      - OLLAMA_BASE_URL=http://ollama:11434
    stdin_open: true
    tty: true
    restart: unless-stopped

volumes:
  ollama_data: