#./backend/Dockerfile
FROM node:20-slim

WORKDIR /app

# Install system deps Prisma needs
RUN apt-get update \
    && apt-get install -y openssl \
    && rm -rf /var/lib/apt/lists/*

COPY package*.json ./
RUN npm ci

COPY . .

RUN npx prisma generate

EXPOSE 5000
CMD ["npm", "run", "dev"]