FROM python:3.12-slim

WORKDIR /app

# Install system dependencies for PDF, image processing
RUN apt-get update && apt-get install -y \
    curl \
    libmagic1 \
    poppler-utils \
    libgl1 \
    libglib2.0-0 \
    && rm -rf /var/lib/apt/lists/*

COPY requirements.txt ./
RUN pip install --no-cache-dir -r requirements.txt

COPY . .

EXPOSE 3000

CMD ["python", "main.py"]